### ISSUE TITLE
Dashboard should show incomplete requests first, followed by completed requests

### ISSUE THREAD

**Issue by AndrewEckart** [ssl-hep/ServiceX_App#114]
# Story
_As a ServiceX user I want to view my ongoing requests at the top of the dashboard, followed by any completed requests._

# Acceptance Criteria
1. New column `finish_time` on the `requests` table
2. New migration script that works in both upgrade/downgrade directions
3. Finish time is set when at the same time status is set to `'Complete'`.
4. Dashboard queries for requests in descending order of finish time

# Assumptions
1. When we do a `SELECT * from requests ORDER BY finish_time DESC` against the requests table, records with a `finish_time` of `NULL` are returned first. 

**Note:** This is not part of the SQL standard, but it is the default behavior of PostgreSQL. However, SQLite (and MySQL, MariaDB, etc.) will place null values at the end when sorting in descending order, so they will return all completed requests first, followed by all incomplete requests. See this article for more details:
https://learnsql.com/blog/how-to-order-rows-with-nulls/

**Comment by BenGalewsky** [comment]
What about a check box to hide completed requests?

**Comment by AndrewEckart** [comment]
> What about a check box to hide completed requests?

That's a good idea (as well as other filters). Our only limitation is that all filtering must be done server-side because the queries are paginated.
