### ISSUE TITLE
Status in dashboard is not updating automatically

### ISSUE THREAD

**Issue by kyungeonchoi** [ssl-hep/ServiceX_App#162]
# Story
Status of ServiceX request is not updating automatically. User needs to refresh the webpage to get the updated status.

# Acceptance Criteria
Status is automatically updating.

# Assumptions
Some changes in the backend might be the reason but not sure exact source.

**Comment by ivukotic** [comment]
fixed with https://github.com/ssl-hep/ServiceX_App/pull/167
