### ISSUE TITLE
Distinguish between API resources and web frontend

### ISSUE THREAD

**Issue by AndrewEckart** [ssl-hep/ServiceX_App#51]
# Story
_As a ServiceX developer I want to distinguish between frontend routes and API resources_

# Acceptance Criteria
1. API resources are placed in a subdirectory, e.g. `https://<servicex-host>/api/v1/servicex/transformation`
2. User management API endpoints should be organized under `api/v1/user/...`

# Assumptions
1. A subdirectory is preferable to a subdomain (`api.<servicex-host>`) because both are being served by the same Flask app.

**Comment by BenGalewsky** [comment]
We need to make sure whatever structure we use works with our Ingres rules. The Ingres only exposes protected endpoints. There are a whole series of endpoints that are for internal use and therefore don't check authentication
